name: Suraj AI CI/CD

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        # 1. Checkout code
        steps:
            - name: Checkout code
              uses: actions/checkout@v5.0.0
            
        # 2. Create .env file
            - name: Create .env file
              run: |
                echo "OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}}" >> .env
                echo "CLOUDINARY_CLOUD_NAME=${{secrets.CLOUDINARY_CLOUD_NAME}}" >> .env
                echo "CLOUDINARY_API_SECRET=${{secrets.CLOUDINARY_API_SECRET}}" >> .env
                echo "CLOUDINARY_API_KEY=${{secrets.CLOUDINARY_API_KEY}}" >> .env 
            
        # 3. Test Endpoint
            - name: Set up python
              uses: actions/setup-python@v6.0.0
              with:
                python-version: 3.12
            
            - name: Install dependencies
              run: |
                pip install -r requirements.txt

            - name: Run test with pytest
              run: |
                pytest -v --maxfail=1 --disable-warnings
            